### ISSUE TITLE
Link to profile not working for Kunena 4.x

### ISSUE THREAD

**Issue by C-Lodder** [JoomJunk/shoutbox#160]

**Comment by C-Lodder** [comment]
Done more testing on this. It works perfectly fine if SEF is enabled.

If URL Rewriting is enabled, it will throw a 404 error unless `htaccess.txt` is renamed to `.htaccess`.

This was the only instance of the error I could find.

@wilsonge - Can you please test this and confirm. If you have the same result, the issue can be closed

**Comment by wilsonge** [comment]
The parameter that says this only works if you rename .htaccess to htaccess.txt only works if do it :O no way :P Replicated and closed

**Comment by betteryouthanme** [comment]
The user link is still wrong?!
Shoutbox links to /index.php/component/kunena/user/1-test

e.g Kunena Latest module to /index.php/forum/user/1-test

If i try user link right now i get a blank page with a message saying:
The page cannot be displayed because an internal server error has occurred.

Check rprclan.com. Thanks

**Comment by C-Lodder** [comment]
@betteryouthanme

1. Do you have SEF URL's enabled?
2. Is you htaccess file called `htaccess.txt` or `.htaccess`?

**Comment by betteryouthanme** [comment]
Yes SEF is enabled
Tried with both htaccess.txt and .htaccess

**Comment by C-Lodder** [comment]
Fixed. about to release the update now
